[2023-03-27T18:14:20.701-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.run_docker manual__2023-03-27T22:14:17.336673+00:00 [queued]>
[2023-03-27T18:14:20.708-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.run_docker manual__2023-03-27T22:14:17.336673+00:00 [queued]>
[2023-03-27T18:14:20.708-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T18:14:20.708-0400] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-27T18:14:20.709-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T18:14:20.715-0400] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): run_docker> on 2023-03-27 22:14:17.336673+00:00
[2023-03-27T18:14:20.721-0400] {standard_task_runner.py:55} INFO - Started process 7270 to run task
[2023-03-27T18:14:20.725-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_pipeline', 'run_docker', 'manual__2023-03-27T22:14:17.336673+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/pipeline.py', '--cfg-path', '/var/folders/8z/pwbx6b3n3mnd1g1f397fv1100000gn/T/tmpb75fowun']
[2023-03-27T18:14:20.726-0400] {standard_task_runner.py:83} INFO - Job 20: Subtask run_docker
[2023-03-27T18:14:20.761-0400] {task_command.py:388} INFO - Running <TaskInstance: air_quality_pipeline.run_docker manual__2023-03-27T22:14:17.336673+00:00 [running]> on host srivardhans-air.starry-inc.net
[2023-03-27T18:14:20.792-0400] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yourname
AIRFLOW_CTX_DAG_ID=air_quality_pipeline
AIRFLOW_CTX_TASK_ID=run_docker
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T22:14:17.336673+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T22:14:17.336673+00:00
[2023-03-27T18:14:20.793-0400] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/8z/pwbx6b3n3mnd1g1f397fv1100000gn/T
[2023-03-27T18:14:20.793-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker-compose -f "/Users/srivardhan/Desktop/Masters/Masters Project/Kafka Implementation/kafka-pipeline-examples/producer-consumer/docker-compose.yml" up -d']
[2023-03-27T18:14:20.802-0400] {subprocess.py:86} INFO - Output:
[2023-03-27T18:14:20.985-0400] {subprocess.py:93} INFO - fork/exec /Applications/Docker.app/Contents/Resources/bin/com.docker.cli: bad file descriptor
[2023-03-27T18:14:20.986-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-27T18:14:20.992-0400] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-27T18:14:20.994-0400] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_pipeline, task_id=run_docker, execution_date=20230327T221417, start_date=20230327T221420, end_date=20230327T221420
[2023-03-27T18:14:21.000-0400] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task run_docker (Bash command failed. The command returned a non-zero exit code 1.; 7270)
[2023-03-27T18:14:21.006-0400] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-27T18:14:21.021-0400] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
