[2023-03-28T14:47:17.672-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: air_quality_pipeline.run_producer manual__2023-03-28T18:47:14.789778+00:00 [queued]>
[2023-03-28T14:47:17.681-0400] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: air_quality_pipeline.run_producer manual__2023-03-28T18:47:14.789778+00:00 [queued]>
[2023-03-28T14:47:17.681-0400] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T14:47:17.681-0400] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-28T14:47:17.681-0400] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T14:47:17.691-0400] {taskinstance.py:1303} INFO - Executing <Task(BashOperator): run_producer> on 2023-03-28 18:47:14.789778+00:00
[2023-03-28T14:47:17.698-0400] {standard_task_runner.py:55} INFO - Started process 48449 to run task
[2023-03-28T14:47:17.707-0400] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'air_quality_pipeline', 'run_producer', 'manual__2023-03-28T18:47:14.789778+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/pipeline.py', '--cfg-path', '/var/folders/8z/pwbx6b3n3mnd1g1f397fv1100000gn/T/tmp_nrsqhr1']
[2023-03-28T14:47:17.709-0400] {standard_task_runner.py:83} INFO - Job 56: Subtask run_producer
[2023-03-28T14:47:17.756-0400] {task_command.py:388} INFO - Running <TaskInstance: air_quality_pipeline.run_producer manual__2023-03-28T18:47:14.789778+00:00 [running]> on host srivardhans-air.starry-inc.net
[2023-03-28T14:47:17.797-0400] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=yourname
AIRFLOW_CTX_DAG_ID=air_quality_pipeline
AIRFLOW_CTX_TASK_ID=run_producer
AIRFLOW_CTX_EXECUTION_DATE=2023-03-28T18:47:14.789778+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-28T18:47:14.789778+00:00
[2023-03-28T14:47:17.798-0400] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/8z/pwbx6b3n3mnd1g1f397fv1100000gn/T
[2023-03-28T14:47:17.799-0400] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 "/Users/srivardhan/Desktop/Masters/Masters Project/Kafka Implementation/kafka-pipeline-examples/producer-consumer/producer.py"']
[2023-03-28T14:47:17.812-0400] {subprocess.py:86} INFO - Output:
[2023-03-28T14:47:59.736-0400] {subprocess.py:93} INFO - Fetching Data from Purple Air sensors
[2023-03-28T14:47:59.740-0400] {subprocess.py:93} INFO - Sending sensor data : 128679
[2023-03-28T14:47:59.741-0400] {subprocess.py:93} INFO - Sending sensor data : 42145
[2023-03-28T14:47:59.742-0400] {subprocess.py:93} INFO - Sending sensor data : 103092
[2023-03-28T14:47:59.742-0400] {subprocess.py:93} INFO - Sending sensor data : 33861
[2023-03-28T14:47:59.743-0400] {subprocess.py:93} INFO - Sending sensor data : 72009
[2023-03-28T14:47:59.744-0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-03-28T14:47:59.744-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/site-packages/requests/models.py", line 971, in json
[2023-03-28T14:47:59.745-0400] {subprocess.py:93} INFO -     return complexjson.loads(self.text, **kwargs)
[2023-03-28T14:47:59.746-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/json/__init__.py", line 348, in loads
[2023-03-28T14:47:59.746-0400] {subprocess.py:93} INFO -     return _default_decoder.decode(s)
[2023-03-28T14:47:59.747-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/json/decoder.py", line 337, in decode
[2023-03-28T14:47:59.748-0400] {subprocess.py:93} INFO -     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[2023-03-28T14:47:59.748-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/json/decoder.py", line 355, in raw_decode
[2023-03-28T14:47:59.749-0400] {subprocess.py:93} INFO -     raise JSONDecodeError("Expecting value", s, err.value) from None
[2023-03-28T14:47:59.750-0400] {subprocess.py:93} INFO - json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[2023-03-28T14:47:59.750-0400] {subprocess.py:93} INFO - 
[2023-03-28T14:47:59.752-0400] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-03-28T14:47:59.754-0400] {subprocess.py:93} INFO - 
[2023-03-28T14:47:59.755-0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-03-28T14:47:59.755-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/Desktop/Masters/Masters Project/Kafka Implementation/kafka-pipeline-examples/producer-consumer/producer.py", line 22, in <module>
[2023-03-28T14:47:59.755-0400] {subprocess.py:93} INFO -     data = get_sensor_details(sensor).json()
[2023-03-28T14:47:59.756-0400] {subprocess.py:93} INFO -   File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/site-packages/requests/models.py", line 975, in json
[2023-03-28T14:47:59.756-0400] {subprocess.py:93} INFO -     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
[2023-03-28T14:47:59.756-0400] {subprocess.py:93} INFO - requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[2023-03-28T14:47:59.777-0400] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-28T14:47:59.791-0400] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/srivardhan/opt/anaconda3/envs/kafka-pipeline/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-28T14:47:59.795-0400] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=air_quality_pipeline, task_id=run_producer, execution_date=20230328T184714, start_date=20230328T184717, end_date=20230328T184759
[2023-03-28T14:47:59.805-0400] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task run_producer (Bash command failed. The command returned a non-zero exit code 1.; 48449)
[2023-03-28T14:47:59.854-0400] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T14:47:59.876-0400] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
